### ISSUE TITLE
絵文字ピッカーがところどころ文字化け・表示崩れしている

### ISSUE THREAD

**Issue by EbiseLutica** [YuigaWada/MissCat#2]
# **Describe the bug (概要)**

絵文字ピッカーの絵文字の一部が化けている

# **Todo**

twemoji を代わりに使うほうが気がラクかもしれないです

# Environment

iOS 13.1.3
iPad 6th Generation

**Comment by YuigaWada** [comment]
iOSのバージョンは13?それとも12?

**Comment by Xeltica** [comment]
@YuigaWada バージョン明記を忘れていたので追記しました。ご確認お願いします:pray:
