### ISSUE TITLE
過去の投稿を遡っている最中に投稿があると画面が動く

### ISSUE THREAD

**Issue by atsukotominaga** [YuigaWada/MissCat#21]
過去の投稿を遡っている時に新規投稿があると、画面が動いて見にくい

**Comment by YuigaWada** [comment]
Fixed it. ([fc1c87f27705b42c805f3c572a1b8a1f728322e8](https://github.com/YuigaWada/MissCat/commit/fc1c87f27705b42c805f3c572a1b8a1f728322e8))
