### ISSUE TITLE
どこかのアプデタイミングで絵文字が初期化された

### ISSUE THREAD

**Issue by harunonsystem** [YuigaWada/MissCat#26]
# **Describe the bug (概要)**
ふと気づいたら絵文字(とその履歴)が初期化されていてﾁｬｽﾓﾊｧｰﾜって感じ

# **Possible cause (考えられる原因)**
ぽぺ

# **Todo**
調査含め、見てもらいたい感じです😭(無理そうだったら「よく分からんけど初期化された、ごめんご」でも大丈夫です🙏🙏)

# **Screenshots**
![image](https://user-images.githubusercontent.com/34958457/86915184-81f9b880-c15c-11ea-9c0f-fd3bcaf0307e.png)

![image](https://user-images.githubusercontent.com/34958457/86915190-8625d600-c15c-11ea-95d1-c7026928d6e5.png)

**Comment by YuigaWada** [comment]
マルチアカウント対応前のMissCatはインスタンス情報をどこにも保存してなかったから、マルチアカウント対応の際(v1.1.0→v1.1.1)に絵文字の設定を移行しないようにしちゃった。。。(カスタム絵文字ってインスタンスごとに違うから...)
