### ISSUE TITLE
めいすきー: 一部アカウントでログインできない

### ISSUE THREAD

**Issue by YuigaWada** [YuigaWada/MissCat#28]
# **Describe the bug (概要)**
めいすきー && Adminユーザーだとログインできない

https://misskey.io/notes/89qwvnj7ol

<br>

# **Possible cause (考えられる原因)**
Adminユーザー特有のオブジェクトが引っかかって、jsonの解析に失敗してるっぽい

**Comment by YuigaWada** [comment]
https://misskey.io/notes/89uie2a0ve

**Comment by YuigaWada** [comment]
https://github.com/YuigaWada/MisskeyKit-for-iOS/blob/master/MisskeyKit/APIs/Model/UserModel.swift
と
https://github.com/Leies-202/misskey/blob/mei-m544/src/models/user.ts
を比較すればどっかに差分があるはず

**Comment by YuigaWada** [comment]
ざっと見た感じ
<s>Twitter.userId→Twitter.idになってるとこが原因？</s>

→struct Twitterは使われてなかった...

**Comment by Leies-202** [comment]
すみません、ことの発端たるインスタンス(初代れいすきー)が爆散して、多分改善されても試すことができなさそうです…。(ちなみに2代目インスタンスでは普通にログインできていたりします…。)

**Comment by YuigaWada** [comment]
あらら、マジですか！
とりあえず、再度報告されるまでissueはcloseすることにします
 💦
ありがとうございます〜
